### ISSUE TITLE
Reviewing the Overall Priority of User Stories for Final Submission

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#10]
This Activity is for EPIC #5 

Creating this activity to ensure the overall priority is updated and review the spreadsheet for final submission.

**Comment by sshaikh4** [comment]
The overall priority has been updated and reviewed. This spreadsheet is ready for submission and linked below:

[Team_6_UserStories](https://docs.google.com/spreadsheets/d/1aqNT3ge4IcMxVPmZJMSd4N3F4VvU7upL/edit#gid=263869482)
