### ISSUE TITLE
Creation of Labels

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#11]
This Activity is in-line with EPIC Creating and Maintaining Issues #4 

This activity is to create labels which can be used to assign the issues in future cycle of our software development.
The description for each label created is listed below for a quick reference:
1. MVP - MVP only has the characteristics that are absolutely necessary to meet the users' main demands—considering the different parts of the project as each MVP.
2. EPIC - An "epic" is a substantial work that may be divided into user stories or smaller, easier-to-manage projects. Create an issue for each sub-task and label those issues “Epic”.
3. Activity - Breaking down each task into multiple activities.

**Comment by sshaikh4** [comment]
Moving this activity back to In Progress as @Jhasija9 will be updating the description for this activity.

**Comment by Jhasija9** [comment]
> Moving this activity back to In Progress as @Jhasija9 will be updating the description for this activity.

I think it has a description

**Comment by sshaikh4** [comment]
> > Moving this activity back to In Progress as @Jhasija9 will be updating the description for this activity.
> 
> I think it has a description

@Jhasija9 - The description should be informative, kindly explain the label terms MVP, EPIC and Activity. You can have the SOW as a reference point for the verbiage. Hope this helps!

**Comment by Jhasija9** [comment]
The description is completed and issue is closed
