### ISSUE TITLE
Requirement Elicitation from the available SOW by - Binny

### ISSUE THREAD

**Issue by sshaikh4** [binny-chopra/smarter-university-system#13]
Activity for Create User Stories #6 

Binny will be sharing a list of requirements from the SOW available.

**Comment by binny-chopra** [comment]
1. Manage course syllabi for proactive student information.
2. Track attendance by viewing enrolled students.
3. Input grades individually or in bulk for accurate records.
4. Schedule and manage class sessions to inform students.
5. Upload and manage course materials for easy access.
6. Make real-time syllabus updates as needed.
7. Communicate with students via the system.
8. Access average and extreme grades for assessment.
9. View detailed grade reports for personalized feedback.
10. Mark assignments as 'extra credit' or 'bonus.'
11. Establish discussion forums for collaborative learning.
12. Review and confirm/deny enrollment requests.

**Comment by binny-chopra** [comment]
Updated requirements after removing duplicates and having team discussion:

- Manage course syllabi for proactive student information.			
- Access the list of enrolled students			
- Schedule and manage class sessions to inform students.			
- Make real-time syllabus updates as needed.			
- Access average and extreme grades for assessment.			
- View detailed grade reports for personalized feedback.

**Comment by binny-chopra** [comment]
Updated list of requirements

**Comment by binny-chopra** [comment]
Updated requirements after removing duplicates and having team discussion:

1. Manage course syllabi for proactive student information.
2. Access the list of enrolled students
3. Schedule and manage class sessions to inform students.
4. Make real-time syllabus updates as needed.
5. Access average and extreme grades for assessment.
6. View detailed grade reports for personalized feedback.
