### ISSUE TITLE
Requirement Elicitation from the available SOW by - Sindhuja

### ISSUE THREAD

**Issue by sshaikh4** [binny-chopra/smarter-university-system#15]
Activity for Create User Stories #6 

Sindhuja will be sharing a list of requirements from the SOW available.

**Comment by SindhujaSane** [comment]
As discussed with the team I was responsible to elicit requirements from the available SOW for **Instructor** Role. Below is my list of elicited requirements:

i. Instructors must be able to communicate effectively with students and facilitate communication among students.
ii. Instructors should be able to deliver lectures with support for remote video capabilities for students in different geographical locations.
iii. Instructors are required to maintain a class syllabus page, which should include the date and topic of each lecture.
iv. Instructors must have the ability to enter lecture information at least two months in advance of the semester start and have the flexibility to update this information during the semester.
v. Instructors need to be notified immediately when a student signs up for their course, to keep track of the current enrollment count.
vi. Instructors should be able to access an overview of their course enrollments, including the number of students enrolled and the maximum capacity of the class.
vii. Instructors must be able to view and manage the list of students enrolled in their classes, including students' names and IDs.
viii. Instructors require the functionality to assign students into groups for team assignments and to name these groups.
ix. Instructors need to be able to enter grades for exams, assignments, and quizzes, with the option to do so individually or in bulk.
x. Instructors should have the capability to view grade statistics for assignments, including average, lowest, and highest grades.
xi. Instructors must be able to view all grades for individual students over the course of the semester.
xii. Instructors should be involved in the approval process for students who do not meet the prerequisites but wish to enroll in a class, requiring a dual confirmation system with administrators.

**Comment by SindhujaSane** [comment]
Marking this Activity as closed since the requirements are listed out and completed.
