### ISSUE TITLE
Requirement Elicitation from the available SOW by - Janesh

### ISSUE THREAD

**Issue by sshaikh4** [binny-chopra/smarter-university-system#16]
Activity for Create User Stories #6 

Janesh will be sharing a list of requirements from the SOW available.

**Comment by Jhasija9** [comment]
The Requirements for Teaching Assistant are:
The Teaching Assistant should have access to class information including the number of students enrolled.
The Teaching Assistant should be able to assign groups to students and name the particular group.
The system should allow teaching assistant to enter grades for quizzes, assignments, and exams individually or in bulk.
The Teaching Assistant should be able to view statistics such as average grades, maximum grades, and minimum grades for each assignment and quiz.
The System should allow the Teaching Assistant to view and access all grades throughout the semester.
The teaching assistant should have access to student's personal information to facilitate grading and communication.
The System should allow the Teaching Assistant to access the student dashboard to track students' progress.
