### ISSUE TITLE
Creation of Binary Tree for Prioritizing Requirements by - Binny

### ISSUE THREAD

**Issue by SindhujaSane** [binny-chopra/smarter-university-system#18]
Activity for Prioritize User Stories #5

Binny will be creating a binary tree for Prioritizing Requirements.

**Comment by binny-chopra** [comment]
Utilizing the binary tree algorithm, I've generated the GraphViz representation for prioritizing user stories based on the list of requirements. The initial requirement serves as the root node.

digraph binny_chopra {
  1 -> 2
  1 -> 7
  2 -> 3
  2 -> 4
  3 -> 5
  3 -> 6
  4 -> 8
  4 -> 9
  5 -> L5
  5 -> 10
  6 -> 11
  6 -> 12
  7 -> 13
  7 -> 14
  8 -> L8
  8 -> 15
  9 -> 16
  9 -> 17
  10 -> 18
  10 -> 19
  11 -> 20
  11 -> 21
  12 -> 22
  12 -> 23
  13 -> 24
  13 -> 25
  14 -> 26
  14 -> 27
  15 -> L15
  15 -> 28
  16 -> 29
  16 -> 30
  17 -> 31
  17 -> 32
  18 -> 33
  18 -> 34
}
