### ISSUE TITLE
Creation of Binary Tree for Prioritizing Requirements by Shabnam

### ISSUE THREAD

**Issue by SindhujaSane** [binny-chopra/smarter-university-system#19]
Activity for Prioritize User Stories #5 

Shabnam will be creating a binary tree for Prioritizing Requirements.

**Comment by sshaikh4** [comment]
Using the binary tree algorithm, I have created the binary tree for the list of requirements to prioritize the user stories in GraphViz format. The first requirement is considered as the root node.

digraph shabnam_shaikh {

 1 -> 2
 1 -> 7
 2 -> L2
 2 -> 3
 3 -> 5
 3 -> 4
 5 -> L5
 5 -> 6
 7 -> 9
 7 -> 8
 9 -> 13
 9 -> 10
 8 -> 11
 8 -> 12
 11 -> 30
 11 -> 31
 12 -> 18
 12 -> 20
 13 -> 14
 13 -> 15
 14 -> 17
 14 -> 16
 18 -> 19
 18 -> 32
 19 -> 33
 19 -> 34
 20 -> 22
 20 -> 21
 22 -> 23
 22 -> 26
 21 -> 25
 21 -> 24
 24 -> 28
 24 -> 27
 27 -> L27
 27 -> 29

}

**Comment by sshaikh4** [comment]
Marking this activity as closed.
