### ISSUE TITLE
Software Requirements

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#2]
- This epic encompasses the development of the Student University System (SUS), a comprehensive software solution designed to enhance the interaction between instructors and students, as well as facilitate seamless communication among students themselves. 

- It encompasses features such as class management, allowing students to sign up for available classes, including remote options, and providing a user-friendly interface for students to find and enroll in classes. 
- The system ensures that administrators are promptly informed when a class is nearing full capacity, granting them the ability to manage enrollments and handle enrollment requests from students who may not meet prerequisites. 
- Additionally, SUS empowers instructors by providing a platform to maintain class syllabi, access student lists, and facilitate team assignments. Moreover, it serves as a centralized database for grades, enabling instructors and students to view and manage academic performance throughout the semester. 

This epic is a cornerstone in our commitment to enhancing the educational experience within our university, ensuring efficient and effective communication and management for all stakeholders.

**Comment by Jhasija9** [comment]
I think the description should not involve our team word and it should be a generalized description like you did for the other 2

**Comment by binny-chopra** [comment]
> I think the description should not involve our team word and it should be a generalized description like you did for the other 2

Have a look now at the description.
