### ISSUE TITLE
Creation of Binary Tree for Prioritizing Requirements - Janesh

### ISSUE THREAD

**Issue by SindhujaSane** [binny-chopra/smarter-university-system#21]
Activity for Prioritize User Stories #5

Janesh will be creating a binary tree for Prioritizing Requirements.

**Comment by Jhasija9** [comment]
Here are the commands for a binary tree:
digraph janesh_hasija{
    1-> 2
    1->8
    2->3
    2->R2
    3->7
    3->4
    7->31
    7->R7
    4->5
    4->R4
    5->L5
    5->6
    8->9
    8->13
    9->11
    9->10
    11->14
    11->17
    14->22
    14->16
    22->L22
    22->28
    16->L16
    16->24
    24->26
    24->25
    17->30
    17->33
    33->L33
    33->34
    10->15
    10->12
    12->32
    12->R12
    13->23
    13->18
    23->L23
    23->27
    18->19
    18->29
    19->L19
    19->20
    20->21
    20->R20
}
