### ISSUE TITLE
Creation of Binary Tree for Prioritizing Requirements - Daya

### ISSUE THREAD

**Issue by SindhujaSane** [binny-chopra/smarter-university-system#22]
Activity for Prioritize User Stories #5

Daya will be creating a binary tree for Prioritizing Requirements.

**Comment by Daya-Sagar2357** [comment]
A binary tree has been created from the list of requirements based on priority in GraphViz, as shown below:

digraph dsagar {
    1 -> 7
    1 -> 8
    7 -> 2
    7 -> 3
    3 -> 4
    3 -> 5
    5 -> 13
    5 -> 6
    8 -> 9
    8 -> 10
    9 -> 11
    9 -> 19
    11 -> 30
    11 -> R11
    30 -> 31
    30 -> R30
    19 -> 33
    19 -> R19
    33 -> 34
    33 -> R33
    10 -> 12
    10 -> 14
    12 -> 32
    12 -> 18
    32 -> 15
    32 -> R32
    14 -> 17
    14 -> 21
    17 -> 22
    17 -> 25
    22 -> 16
    22 -> R22
    21 -> 20
    21 -> 29
    20 -> 23
    20 -> 24
    23 -> 28
    23 -> R23
    24 -> 27
    24 -> 26
    
}

Marking this activity as closed.
