### ISSUE TITLE
API Test cases from the values that are clearly outside the specified format

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#28]
This Activity is for EPIC #8

As part of this activity Shabnam will create API test inputs for the parameters in such a way that few test cases will have values that are clearly outside the parameters specified format mentioned in the SOW. Utilising the category partition and boundary value analysis methods.

**Comment by sshaikh4** [comment]
This is a duplicate of Activity #11, we will reuse this activity for future API or Unit Test activities.

**Comment by sshaikh4** [comment]
As mentioned earlier we have used this issues as API Test case activity. The description and Activity name is updated accordingly.

**Comment by sshaikh4** [comment]
The API test cases for values that are outside the specified format is created and listed in the below linked excel spreadsheet. I have referred the Statement of Work to use date and time outside the specified format for these test cases.

[API Test Cases](https://docs.google.com/spreadsheets/d/1qqNqNJRoYm7R4czxXrj8OzN9eZC_KIBi/edit#gid=608825545)
