### ISSUE TITLE
Software Testing

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#3]
We are a group of software testers dedicated to improving the reliability and performance of the Smarter University System. Our goal is to identify and report software issues, suggest enhancements, and ensure a seamless user experience for students, instructors, and administrators. This MVP outlines our activities to perform API Test Inputs and Unit Tests.

**Comment by Daya-Sagar2357** [comment]
API test inputs have been created based on the available parameters. Three test cases were created for the quizzes controller module and a PR has been raised. Closing this MVP.
