### ISSUE TITLE
Identifying Epics for User Requirements - Shabnam

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#30]
This activity is in-line with Epic #6 

Shabnam will identify the epics basis which team members will list the requirements and create user stories in line with the SOW.

**Comment by sshaikh4** [comment]
After reviewing the Statement of Work for the Smarter University System (SUS) below are the list of users using this system. Basis these users our team will focus to identify the requirements and build user stories.

**1. Instructors
2. Students
3. Teaching Assistant
4. Administrator**

The same was discussed with the team, hence I am closing this activity here.
