### ISSUE TITLE
Submitting user stories as team's deliverable

### ISSUE THREAD

**Issue by Daya-Sagar2357** [binny-chopra/smarter-university-system#32]
Activity for #6 - The user stories that have been created from each members' requirement elicitation, analysis and formatting, will be organized into the second deliverable for submission

**Comment by SindhujaSane** [comment]
The following Spreadsheet link has the finalized User Stories by the team.

https://docs.google.com/spreadsheets/d/13jfuTTYTOLd2M9NCBBCDc5EFrtsOHZJq/edit?usp=sharing&ouid=105668311934756662367&rtpof=true&sd=true
