### ISSUE TITLE
Discussing prioritization strategy with the team

### ISSUE THREAD

**Issue by Daya-Sagar2357** [binny-chopra/smarter-university-system#33]
Activity for #5 - The user stories that have been produced so far needs to be prioritized. A strategy to do efficient prioritization, taking each members' priorities into consideration (binary tree method), will be discussed.

**Comment by SindhujaSane** [comment]
Here in this activity, we aim to prioritize our user stories efficiently by incorporating the preferences of each team member. The process is as follows:

- **Individual Trees**: Every team member uses the GraphViz tool to create a binary search tree. This tree shows how they individually prioritize the user stories.

- **Assigning Ranks**: Next, each member gives a rank to every user story in their tree. Lower ranks mean higher priority.

- **Combining Ranks**: We add up the ranks from all team members for each user story.

- **Final Order**: The user story with the smallest total rank becomes our top priority. 
- This approach makes sure everyone's views are included in deciding what we work on first.

**Comment by SindhujaSane** [comment]
Marking this Activity as closed as we have discussed our prioritization strategy.
