### ISSUE TITLE
Creation of spreadsheet showing final priority ranking of user stories

### ISSUE THREAD

**Issue by Daya-Sagar2357** [binny-chopra/smarter-university-system#35]
Activity for #5 - The final combined priority ranking of the user stories will be organised into a spreadsheet to submit as the third deliverable for the project for submission.

**Comment by sshaikh4** [comment]
Each member will update their priority list in the spreadsheet here: [User Stories-Prioritization](https://docs.google.com/spreadsheets/d/1aqNT3ge4IcMxVPmZJMSd4N3F4VvU7upL/edit#gid=263869482)

**Comment by binny-chopra** [comment]
After discussion, the overall priority is assigned to all the User Stories.
