### ISSUE TITLE
Team discussion and brainstorming for API Test inputs

### ISSUE THREAD

**Issue by Daya-Sagar2357** [binny-chopra/smarter-university-system#40]
#8 Discuss methods to cover all test case inputs for the API endpoint such that the methods category partition and boundary value analysis are utilized for full coverage.

**Comment by sshaikh4** [comment]
We discussed as a team to cover the following requirements as part of API test cases:

1. Test cases to mimic both nominal use and invalid use of the API endpoint
2. Test cases that slightly deviate from the format but may be reasonably considered valid from a common sense perspective
3. Test cases from the values that are clearly outside the specified format
