### ISSUE TITLE
Create API test inputs for the parameters specified

### ISSUE THREAD

**Issue by Daya-Sagar2357** [binny-chopra/smarter-university-system#41]
#8 Create API test inputs for the parameters in such a way that all cases are covered. Utilise category partition and boundary value analysis methods. Test cases that slightly deviate from the given format should still be reasonably valid from a common sense perspective.

**Comment by SindhujaSane** [comment]
https://docs.google.com/spreadsheets/d/1qqNqNJRoYm7R4czxXrj8OzN9eZC_KIBi/edit#gid=608825545

**Comment by SindhujaSane** [comment]
Marking this Activity as closed since the API test inputs for the parameters are created such that it covers all the cases.
