### ISSUE TITLE
Write Unit Tests

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#7]
#3 
A Smarter University System project's unit testing guarantees that each feature and component functions as intended, boosting user trust in the stability and dependability of the system. Additionally, it helps find problems early in the development process and address them, which makes the system more reliable and safe in the end.

**Comment by Daya-Sagar2357** [comment]
Unit test cases for the quizzes controller has been created and pushed to the main branch. A corresponding Pull Request has also been created from the fork to the main repository for the test cases.
