### ISSUE TITLE
Create API test inputs 

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#8]
#3 
A crucial part of the quality assurance procedures is the testing of the system boundaries. Test inputs will be created for an API endpoint that exposes a new capability of the SUS that shows an activity stream in the sidebar of the SUS user interface. The test cases are created using the category partition and boundary analysis methods, to be effective in uncovering defects, and ensuring the robustness of the endpoint.

**Comment by sshaikh4** [comment]
All the activities from this EPIC has been completed and we have the list of API test cases ready as part of the deliverable. Hence, closing this EPIC.
